# Generated by Django 6.1.1 on 2026-09-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('oferta', models.BooleanField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
